### ISSUE TITLE
Umgang mit Lösungsskripts

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS23#20]

**Comment by ratnanil** [comment]
Aktuell sehe ich für jede Aufgabe (suffix `_uebung.qmd`) ein mehr oder weniger identisches `_loesung.qmd` File. Der Unterschied ist jeweils in den Chunk Options (`echo: false` und `echo: true`). Es wäre einfacher, lediglich ein File zu haben, und die chunk options im YAML header des jeweiligen Files zu ändern, um die Lösungen frei zu schalten. Siehe auch 0b90224

**Comment by ratnanil** [comment]
```
execute: 
  echo: true   # set to true to show musterlösung
  output: true # set to true to show musterlösung
code-fold: true
code-summary: "Musterlösung"
```
